{% set name = "pytorch-lightning" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 667e1557036b99fe3f46a87b699d8af73cd756331d8d06f547bd6d269119b337

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future  # >=0.17.1
    - packaging
    - numpy  >=1.16.4
    - python >=3.6
    - pyyaml  >=5.1, !=5.4
    - pytorch >=1.3
    - tqdm  >=4.41.0
    - tensorboard >=2.2.0
    - fsspec[http] >=0.8.1
    - torchmetrics >=0.2.0

test:
  imports:
    - pytorch_lightning
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - williamFalcon
    - borda
