{% set name = "pytorch-lightning" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 524eca14edcee055d04de537caa2924de36dec4b3f4a2d9d0e35fb944b8ab6aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - future  # >=0.17.1
    - packaging
    - numpy  >=1.17.2
    - pyyaml  >=5.1
    - pytorch >=1.6
    - tqdm  >=4.41.0
    - tensorboard >=2.2.0
    - fsspec[http] >=2021.05.0, !=2021.06.0
    - torchmetrics >=0.4.1
    - pyDeprecate ==0.3.1

test:
  imports:
    - pytorch_lightning
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Lightning is a way to organize your PyTorch code to decouple the science code from the engineering.
     It's more of a style-guide than a framework.

    In Lightning, you organize your code into 3 distinct categories:

    1. Research code (goes in the LightningModule).
    2. Engineering code (you delete, and is handled by the Trainer).
    3. Non-essential research code (logging, etc. this goes in Callbacks).

    Although your research/production project might start simple, once you add things like GPU AND TPU training,
     16-bit precision, etc, you end up spending more time engineering than researching.
     Lightning automates AND rigorously tests those parts for you.

    Overall, Lightning guarantees rigorously tested, correct, modern best practices for the automated parts.

    Documentation
    -------------
    - https://pytorch-lightning.readthedocs.io/en/latest
    - https://pytorch-lightning.readthedocs.io/en/stable

extra:
  recipe-maintainers:
    - williamFalcon
    - borda
