{% set name = "pytorch-lightning" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f1010a49b1d1ee4a09653cfa00c438d1117b509e16661e271df587403f8d9e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future >=0.17.1
    - numpy >=1.16.4
    - python >=3.6
    - pyyaml >=3.13
    - tensorboard >=1.14
    - pytorch >=1.1
    - tqdm >=4.41.0
    - packaging

test:
  imports:
    - pytorch_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - williamFalcon
    - borda
